### ISSUE TITLE
Search 

### ISSUE THREAD

**Issue by pheianox** [x64Bits/solid-icons#13]
1.  Firefox opens "Quick find" when I press '/' for search focus
Or maybe my desktop enviroment (XFCE) has some hidden shortcuts I don't know about 
I would be greateful if you could add Ctrl + K shortcut for search 

2. Could you provide category specific search? 
Beacuse sometimes you want specific icon pack so that icons stay consistent

Thank you for you time

**Comment by pheianox** [comment]
By "category specific search" I mean search icons in specific pack

**Comment by x64Bits** [comment]
Hi @pheianox, thanks for the suggestions, in fact i'm currently working on change the hotkey to focus the search input.

About the search categories, it would not be clear whether to implement it because not all packages share styles, it would be necessary to implement these categories manually, for example for Outline, Fill, Solid, Two Tone and more.

**Comment by pheianox** [comment]
Thanks
