### ISSUE TITLE
RiUser related icons have their name and export generated incorrectly

### ISSUE THREAD

**Issue by toondkn** [x64Bits/solid-icons#43]
All `RiUser` (and maybe other) icons have an incorrect component export name.

My existing app broke after upgrading this package from `1.0.4` to `1.0.8` due to a bunch of `RiUser` icons that were used, that are now no longer exported. It appears they are not truly gone, they just get mangled in the icon generation process I assume.

You can verify this issue by visiting eg. [https://solid-icons.vercel.app/search/RiUser](https://solid-icons.vercel.app/search/RiUser), please notice how:
- invalid import statements are shown: `import { RiUser & FacesAccountBoxFill } from 'solid-icons/ri'`,
- invalid component names are used as example: `<RiUser & FacesAccountBoxFill />`.

Workaround: keep using version `1.0.4`, as this issue presents itself in `1.0.5`, `1.0.6.`, `1.0.7` and `1.0.8`.

**Comment by x64Bits** [comment]
Hi @toondkn thanks for notice about, i fixed this issue on the `1.0.7`, recently i'm installed the lib on the codesandbox and the remix package looks well, can you take a look, i need to publish a new version of the icons used on the web explorer because have the error that you mentioned. 

codesandbox: https://codesandbox.io/p/sandbox/solid-icons-color-sbc4fu?file=%2Fnode_modules%2Fsolid-icons%2Fri%2Findex.d.ts%3A1%2C1
