### ISSUE TITLE
Does not work with latest Astro & Solid

### ISSUE THREAD

**Issue by marvin-j97** [x64Bits/solid-icons#46]
Reproduction: https://github.com/marvin-j97/solid-1.7-icons

Icon is invisible.
Changing `client:load` to `client:only` fixes it.

**Comment by marvin-j97** [comment]
Probably related to https://github.com/x64Bits/solid-icons/issues/41 ?
Maybe https://github.com/x64Bits/solid-icons/issues/45 as well

**Comment by densumesh** [comment]
the svg path seems to be in quotes in the html causing the svg to not render. 
![image](https://github.com/x64Bits/solid-icons/assets/25559111/497a3843-dadc-4c98-9046-54be973c8216)

**Comment by x64Bits** [comment]
Hello, I am very aware of the problem that solid-icons are having when used in astro.

I hadn't given an answer because I wanted to reply with the solution, but it's taking me longer to figure out why this is happening, I think it's a problem in the build because in solid you can't just do `<svg>{iconSrc.c}< /svg>`, I'm concentrating on fixing this, I'll bring news over the weekend, thanks!

**Comment by x64Bits** [comment]
Hi everyone, i comment here about it https://github.com/x64Bits/solid-icons/issues/41#issuecomment-1620939575

**Comment by marvin-j97** [comment]
Working for me @x64Bits :+1:
